name: stroke-mlflow
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - numpy>=1.23,<3
      - pandas>=2.0,<3
      - scikit-learn>=1.3,<2
      - joblib>=1.2,<2
