digest: '36123876'
name: dataset
profile: '{"num_rows": 160, "num_elements": 1280}'
schema: '{"mlflow_colspec": [{"type": "long", "name": "age", "required": true}, {"type":
  "long", "name": "hypertension", "required": true}, {"type": "long", "name": "heart_disease",
  "required": true}, {"type": "double", "name": "avg_glucose_level", "required": true},
  {"type": "double", "name": "bmi", "required": true}, {"type": "double", "name":
  "feature_0", "required": true}, {"type": "double", "name": "feature_1", "required":
  true}, {"type": "double", "name": "feature_2", "required": true}]}'
source: '{"tags": {"mlflow.user": "root", "mlflow.source.name": "modelling.py", "mlflow.source.type":
  "LOCAL"}}'
source_type: code
