digest: 643e0c10
name: dataset
profile: '{"num_rows": 40, "num_elements": 320}'
schema: '{"mlflow_colspec": [{"type": "long", "name": "age", "required": true}, {"type":
  "long", "name": "hypertension", "required": true}, {"type": "long", "name": "heart_disease",
  "required": true}, {"type": "double", "name": "avg_glucose_level", "required": true},
  {"type": "double", "name": "bmi", "required": true}, {"type": "double", "name":
  "feature_0", "required": true}, {"type": "double", "name": "feature_1", "required":
  true}, {"type": "double", "name": "feature_2", "required": true}]}'
source: '{"tags": {"mlflow.user": "ACER", "mlflow.source.name": "d:/Downloads/Workflow-CI/MLProject/modelling.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "c7be2da3f2279810c8cef5bfe9cc255854f5ec0a"}}'
source_type: code
